# Server 配置
server:
  port: 8080

# Spring配置
spring:
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://123.207.73.162:3306/qs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: Wjianwu&&z*l@true88
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          db-type: mysql
          merge-sql: false
  # 缓存配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50      # 最大连接数
        max-wait: 3000ms    # 最大阻塞时间等待时间
        max-idle: 20        # 最大空闲连接
        min-idle: 2         # 最少空闲连接
    timeout: 5000ms         # 连接超时时间

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*
  type-aliases-package: com.wjianwu.qs.entity
  configuration:
    map-underscore-to-camel-case: true



##日志配置
#logging:
#  file:
#    # 存放文件的最大天数
#    max-history: 15
#    # 存放文件的最大Size
#    max-size: 20MB
#  # 存放文件的位置
#  path: D:\GitProjects\logs
#  pattern:
#    # 输出到控制台的格式
#    console: "wjianwu - %d{yyyy-MM-dd HH:mm:ss} -%-4r  [%t]  %-5level %logger{36} - %msg%n"
#  level:
#    root: info
#    com.wjianwu.core: debug